- name: Vhost-Net Setup
  hosts: pvp-host
  vars_files:
    - vars/pvp-settings.yml
  tasks:
  - name: Include guest vars
    include_vars:
      file: vars/guest.yml
      name: guest_vars
  - name: Include trex vars
    include_vars:
      file: vars/trex.yml
      name: trex_vars
  - debug: 
      msg: Debug mode is enabled
  - name: install dependencies
    yum:
      name:
        - qemu-kvm
        - libvirt
        - iperf3
        - virt-install
        - libguestfs-tools-c
        - python3-lxml
      state: installed

# Create and start the default network
  - name: Destroy previous default network
    virt_net:
      state: absent
      name: pvp-mgt

  - name: Define default network
    virt_net:
      command: define
      name: pvp-mgt
      xml: "{{ lookup('template', 'pvp-mgt-net.xml.j2') }}"

  - name: Start mgt network
    virt_net:
      state: active
      name: pvp-mgt

# Create and start the default network
  - name: Destroy previous private networks
    virt_net:
      state: absent
      name: pvp-priv1

  - name: Undefine previous private networks
    virt_net:
      command: undefine
      name: pvp-priv1

  - name: Define p1 network
    virt_net:
      command: define
      name: pvp-priv1
      xml: "{{ lookup('template', 'pvp-priv1.xml.j2') }}"

  - name: Start p1 network
    virt_net:
      state: active
      name: pvp-priv1

  - name: Destroy previous private networks
    virt_net:
      state: absent
      name: pvp-priv2

  - name: Undefine previous private networks
    virt_net:
      command: undefine
      name: pvp-priv2

  - name: Define p2 network
    virt_net:
      command: define
      name: pvp-priv2
      xml: "{{ lookup('template', 'pvp-priv2.xml.j2') }}"

  - name: Start mgt network
    virt_net:
      state: active
      name: pvp-priv2

  - name: Delete bridge1
    command: ip link del pvp-priv1
    ignore_errors: yes

  - name: Delete bridge1
    command: ip link del pvp-priv2
    ignore_errors: yes

  - name: Create bridge1
    command: ip link add name pvp-priv1 type bridge

  - name: Start bridge1
    command: ip link set pvp-priv1 up

  - name: Create bridge2
    command: ip link add name pvp-priv2 type bridge

  - name: Start bridge2
    command: ip link set pvp-priv2 up

  - import_tasks: config_vm.yml
    vars:
      vm_extra_vars: guest.yml
      vm_template: guest.xml.j2

  - import_tasks: config_vm.yml
    vars:
      vm_extra_vars: trex.yml
      vm_template: trex.xml.j2

# Add the guest to the inventory to continue running commands in it
  - name: Add guest to inventory
    add_host:
      name: "{{ guest_vars.vm_ip }}"
      group: guests
      ansible_ssh_pass: "{{ guest_vars.vm_root_password }}"
      ansible_ssh_user: root
      ansible_ssh_common_args: -o UserKnownHostsFile="/dev/null" -o StrictHostKeyChecking=no

  - name: Add trex to inventory
    add_host:
      name: "{{ trex_vars.vm_ip }}"
      group: trex
      ansible_ssh_pass: "{{ trex_vars.vm_root_password }}"
      ansible_ssh_user: root
      ansible_ssh_common_args: -o UserKnownHostsFile="/dev/null" -o StrictHostKeyChecking=no

- name: Vhost-User Guest Setup
  hosts: guests
  vars_files:
    - vars/guest.yml
  tasks:

  - name: install repository
    yum_repository:
      name: virtio-auto-{{ index }}
      description: virtio-auto repository
      baseurl: "{{ item }}"
      gpgcheck: no
    loop: "{{ os_repos }}"
    loop_control:
      index_var: index

  - import_tasks: install_lnst.yml
    vars:
      repo: "{{ lnst_repo }}"
      ref: master


- name: PVP  TRex Setup
  hosts: trex
  vars_files:
    - vars/trex.yml
  tasks:

  - name: install repository
    yum_repository:
      name: virtio-auto-{{ index }}
      description: virtio-auto repository
      baseurl: "{{ item }}"
      gpgcheck: no
    loop: "{{ os_repos }}"
    loop_control:
      index_var: index

  - import_tasks: install_lnst.yml
    vars:
      repo: "{{ lnst_repo }}"
      ref: " {{ lnst_ref }}"

  - name: Install dependencies
    yum:
      state: installed
      name:
        - git
        - python3
        - python3-devel
        - driverctl
        - libvirt-devel
        - libnl3-devel

